### ISSUE TITLE
It does not work! Can anyone create one that works?

### ISSUE THREAD

**Issue by TUNA-NOPE** [GooogIe/Spotify-Login-API#1]
It does not work! Can anyone create one that works?

**Comment by dieser-niko** [comment]
Looks like Spotify uses Google Captcha. I only know one way to get around that and it's selenium. Not a very elegant way..

**Comment by TUNA-NOPE** [comment]
`from pyppeteer import launch # pip install pyppeteer
import asyncio

async def main():
        browser = await launch({
            'headless': True, # set off the gui
        })
        page = await browser.newPage()
        await page.goto('https://accounts.spotify.com/en/login')
        await page.waitForSelector('#login-username', {'visible': True})
        await page.type('#login-username', self.username)
        await page.type('#login-password', self.password)
        await page.click('#login-button')
        finalResponse = await page.waitForResponse('https://accounts.spotify.com/login/password')

        if finalResponse.status != 200:
            print("AUTHENTICATION FAILURE")
            await browser.close()
            return

        cookies = await page.cookies()
        await browser.close() 

asyncio.get_event_loop().run_until_complete(main())`

**Comment by dieser-niko** [comment]
Dude, listen. Spotify uses Google Captcha. This here doesn't work anymore. If you need to use the Spotify API, try [spotipy](https://pypi.org/project/spotipy/)
